apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  namespace: guestbook-ns
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
  selector:
    app: guestbook-ui
